---
abstract: 'Template framework for Moose objects'
author:
  - 'Ian Sillitoe <isillitoe@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Templated
provides:
  MooseX::Templated:
    file: lib/MooseX/Templated.pm
    version: 0.03
  MooseX::Templated::Role:
    file: lib/MooseX/Templated/Role.pm
  MooseX::Templated::View:
    file: lib/MooseX/Templated/View.pm
  MooseX::Templated::View::TT:
    file: lib/MooseX/Templated/View/TT.pm
requires:
  File::Slurp: 9999.13
  File::Where: 1.16
  Moose: 0.60
  Path::Class: 0.16
  Readonly: 1.03
  Template: 2.20
  Test::More: 0.86
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
