---
abstract: 'template-based rendering of Moose objects'
author:
  - 'Ian Sillitoe  C<< <isillitoe@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Templated
no_index:
  directory:
    - inc
    - t
requires:
  Moose: '1.0'
  MooseX::Role::Parameterized: 0
  MooseX::Types::Path::Class: 0
  Path::Class: '0.16'
  Template: '2.20'
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.06'
